name: Execute CumulusCI Flow
description: 'Execute a named CumulusCI flow'
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: true
    default: '3.59.0'
  sfdx-version:
    description: 'version of SFDX to install'
    required: true
    default: '7.135.0'
  dev-hub-auth-url:
    description: 'SFDX auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org config to use'
    required: true
  flow-name:
    description: 'Name of the CumulusCI flow to execute'
    required: true
runs:
    using: "composite"
    steps:
      - name: Install sfdx
        run: |
          npm install -g 'sfdx-cli@${{ inputs.sfdx-version }}'
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install CumulusCI
        run: |
          pip install 'cumulusci==${{ inputs.cumulusci-version }}'
        shell: bash
      - name: Authenticate to Dev Hub
        run: |
          echo '${{ inputs.dev-hub-auth-url }}' > sfdx_auth
          sfdx force:auth:sfdxurl:store -f sfdx_auth -d
          rm sfdx_auth
        shell: bash
      - name: Run Flow
        env:
          CUMULUSCI_SERVICE_github: '{"username": "${{ github.actor }}", "token": "${{ github.token }}", "email": "cci@github.actions" }'
        run: |
          cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }}
        shell: bash
      - name: Delete Scratch Org
        if: ${{ always() }}
        run: |
          cci org scratch_delete ${{ inputs.org-name }}
        shell: bash
